import { useState } from "react";
import type { MouseEventHandler } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { random } from "lodash";
import { LazyImage } from "@/components/RandomFox";

// generate a random Function between 1 and 123
const myRandom = () => random(1, 123);

//generate simple unique id
const generateId = () => Math.random().toString(36).substr(2, 9);

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<IFoxImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = () => {

    const newImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${myRandom()}.jpg`,
    };

    setImages([...images, newImageItem]);
    window.plausible("Signup")
  }

  return (
    <div>
      <Head>
        <title>Random Fox App</title>
        <meta name="description" content="Generated by Random Fox App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <script defer
        data-domain="domain1.com,domain2.com,domain3.com"
        src="https://plausible.io/js/script.js"
      ></script>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <button onClick={addNewFox}>Add new fox</button>
        {images.map(({ id, url }) => (
          <div key={id} className="p-4">
            <div className="relative h-64 w-full">
              <LazyImage
                src={url}
                alt="Random fox"
                width={320}
                height={180}
                className="rounded object-cover"
              />
            </div>
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
